Fix delete; clarify extension
cds-hooks/docs pull request #554
Opened 2021-01-15 16:37 UTC by mattvarghese

* Deleting a resource should use a resource with just resourceType and id
* Extension examples updated to always have a reverse uri naming convention

2021-01-15 19:48 UTC, ssmillard reviewed
For extensions, Would it be possible to have a structure such as:	"extension": [
		{
			"uri": "com.example.timestamp",
			"value": "2017-11-27T22:13:25Z"
		},
		{
			"uri": "com.cds-hooks.sandbox.myextension-practitionerspecialty",
			"value": "gastroenterology"
		}]

2021-01-15 21:11 UTC, dennispatterson commented
@ssmillard we had a bit of discussion about the extensions topic and I dug up https://github.com/cds-hooks/docs/issues/133 and https://github.com/cds-hooks/docs/issues/89, where there was a decision made to handle it this way (for both extensions and prefetch) vs the uri/value pairs mechanism.

2021-01-18 18:02 UTC, isaacvetter commented
Related: http://hl7.org/fhir/us/davinci-crd/2019May/hooks.html#propose-alternate-request

The issue with:
1. Deleting a resource should use a resource with just resourceType and id

Is that the same element name (`resource`) using different data types between delete vs create/update is inelegent depending upon the dev stack. 

An alternative to the proposal would be to introduce a new element name (e.g. resourceLocation) to be used for deletes, which could also enable a transition path, and cds service could even provide both. 

If we make any changes, we should ensure that CRD stays in sync as well.

2021-01-20 16:45 UTC, isaacvetter commented
@dennispatterson , @brynrhodes and I talked through this issue. 

Ultimately, it is awkward for developers to treat the same `resource` element as either a resource "location" (aka ProcedureRequest/123) or as a full resource. We believe that delete suggestions are not yet widely implemented. Specific to delete suggestions, from a developer perspective, constructing a shell resource withonly a resource type and id 

```
`resourceId` | CONDITIONAL | *string* | A relative reference to the relevant resource in the suggestion. SHOULD be provided for delete suggestions. 
`resource` | OPTIONAL | *object* | A FHIR resource. When the `type` attribute is `create`, the `resource` attribute SHALL contain a new FHIR resource to be created.  For `update`, this holds the updated resource in its entirety and not just the changed fields. Use of this field to communicate a string of a FHIR id for delete suggestions is DEPRECATED and `resourceId` SHOULD be used instead.
```
~~For `delete`, this SHALL be the id of the resource to remove. In hooks where only one "content" resource is ever relevant, this attribute MAY be omitted for `delete` action types only.~~

Todo:
- @isaacvetter : create jira issue

2021-01-20 17:06 UTC, isaacvetter commented
Hey @ssmillard,

>For extensions, Would it be possible to have a structure such as: "extension": [

Yes, definitely. The idea is that everything within the extension element is entirely yours to do with as you want.

2021-01-26 15:39 UTC, dennispatterson requested changes

2021-01-26 15:39 UTC, dennispatterson commented on docs/specification/current.md
> +`resourceId` | CONDITIONAL | *string* | A relative reference to the relevant resource in the suggestion. SHOULD be provided for when the `type` attribute is `delete`.
Minor wordsmithing
```suggestion
`resourceId` | CONDITIONAL | *string* | A relative reference to the relevant resource. SHOULD be provided when the `type` attribute is `delete`. 
```

2021-01-26 15:39 UTC, dennispatterson commented on docs/specification/current.md
> +	}
Get rid of the extra bracket
```suggestion
```

2021-02-10 17:10 UTC, mattvarghese commented
Hey Folks - are we all agreed on this change? Can we move ahead with this pull request?

2021-02-10 17:34 UTC, dennispatterson approved these changes

2021-02-11 22:17 UTC, isaacvetter approved these changes

2021-02-11 22:18 UTC, merged